# プロジェクト2：コロナ禍が若年層の雇用に与えた影響 {#sec-covid-19-labor-market}

## 背景と目的

　2019年末に始まったコロナ禍は、企業が休業やリモートワークへの切り替えを余儀なくされるなど、雇用環境に大きな影響を与えました。特に新卒者の就職市場では、小売、レジャー、空運など外出制限の影響を受けやすい業界・業種で、採用計画の削減や採用中止が相次ぎました。  
　本研究では、コロナ禍以降に卒業した世代が賃金・就業・雇用形態の面で不利だったかを、明らかにすることを目的として、全国就業実態パネル調査（JPSED）で定量的評価を行いました。

## 使用データと手法

　使用したデータは次のとおりです。

- データ：国就業実態パネル調査（JPSED）の個票データのうち、2017年から2022年調査までの6年分を使用。
- 2012年以降卒・35歳未満を分析対象とした（n=32,714）。

分析に当たって3つのリサーチクエスチョンを設定し、それぞれ次のような分析手法を採用しました。

1. **RQ1（賃金への影響）**: コロナ禍以降に就職した世代は、それ以前の世代と比べて賃金が低下したか。
    - 分析手法として、タイプIIトービットモデルを使用しました^[タイプIIトービットモデルについては @sec-type2-tobit を参照してください。]。
2. **RQ2（就業状態への影響）**: コロナ禍以降に就職した世代は、それ以前の世代と比べて就業率が低下したか。
    - 分析手法として、多項ロジットモデルを使用しました。
3. **RQ3（非正規雇用率への影響）**: コロナ禍以降に就職した世代は、それ以前の世代と比べて非正規雇用率が上昇したか。
    - 分析手法として、プロビットモデルを使用しました。

また、回答者を卒業年にしたがって「2018年以前」「2019年（基準）」「2020年」「2021年」という4つのコホートに分けることで、コロナ禍以降に卒業した世代が雇用面で不利だったかを明らかにすることを目指しました。

## 結果の概要

　本研究では、2020年以降の学卒者の賃⾦は19年卒者と⽐べて有意に低下したとの結果が得られました。加えて、19年卒⼥性と⽐べて21年卒⼥性の⾮正規雇⽤率が有意に増加している事が分りました。新卒⼥性における⾮正規雇⽤率の増加は、就職氷河期の初期にも⾒られた現象であり、影響の⻑期化が懸念される結果でした。一方で、就業率に有意な変化は確認されず、短期的な就業意欲は大きく崩れていないと考えられます。

## 考察

　本研究の結果は、コロナ禍以降に卒業した世代が賃金と雇用形態の面で不利を抱えていることを示唆するものであった。太田ほか[@太田ほか2007]など、就職氷河期をめぐる先行研究で指摘されている初職効果の存在を踏まえると、影響の固定化を避けるための対策が必要になると考えられます。  
　一方、本研究の限界としては2022年調査分までのデータを利用していることが挙げられます。2022年卒以降コホートの追跡、長期の影響を分析することが今後の課題と言えます。また、2023年以降は新卒初任給の上昇傾向が見られるため、最新の調査を用いた分析では異なる結果が得られるのではないかと考えられます^[例えば[「独立行政法人 労働政策研究・研修機構：新規学卒者の賃金」](https://www.jil.go.jp/kokunai/statistics/shuyo/0303.html)を参照。]。
